source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
inhibit_all_warnings!

project 'authLoginComponent'

target 'authLoginComponent_Example' do
   pod 'auth0LoginComponent', :path => '../'
end