source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
inhibit_all_warnings!

project 'authLoginComponent'

target 'authLoginComponent_Example' do
   pod 'auth0LoginComponent', :path => '../'
   
   target 'authLoginComponent_Tests' do
      inherit! :search_paths
      pod 'Quick', '~> 0.8'
      pod 'Nimble', '~> 3.0'
   end
end